import Foundation

struct Server {
    let name: String
    let baseURL: String
    let configuration: [(String, String)]
}

struct Endpoint {
    let name: String
    let server: String
    let feature: String
    let method: String
    let path: String
    let parameters: [String]
    let requestKind: String
    let source: String
}

enum BackendReferenceGenerator {
    static func run() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard let sourceDirectory = value(after: "--source-directory", in: arguments) else {
            throw GeneratorError.invalidArguments
        }
        let stamp = value(after: "--stamp", in: arguments)

        let sourceURL = URL(fileURLWithPath: sourceDirectory)
        let projectRoot = findProjectRoot(startingAt: sourceURL)
        let outputDirectory = value(after: "--output-directory", in: arguments)
            .map(URL.init(fileURLWithPath:))
            ?? projectRoot.appendingPathComponent("BackendAPIReference", isDirectory: true)
        let files = try swiftFiles(in: projectRoot)
        let documents = try files.map { url in (url, try String(contentsOf: url, encoding: .utf8)) }
        let servers = parseServers(documents)
        let protocolClients = parseProtocolClients(documents)
        let endpoints = parseEndpoints(documents, protocolClients: protocolClients, root: projectRoot)

        try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        try writeIndex(servers: servers, endpoints: endpoints, to: outputDirectory)
        for server in servers {
            try writeServerPage(server, endpoints: endpoints.filter { $0.server == server.name }, to: outputDirectory)
        }
        if let stamp {
            try "Generated by BackendReferencePlugin\n".write(to: URL(fileURLWithPath: stamp), atomically: true, encoding: .utf8)
        }
    }

    static func value(after option: String, in arguments: [String]) -> String? {
        guard let index = arguments.firstIndex(of: option), arguments.indices.contains(index + 1) else { return nil }
        return arguments[index + 1]
    }

    static func findProjectRoot(startingAt directory: URL) -> URL {
        let fileManager = FileManager.default
        var candidate = directory
        while candidate.path != "/" {
            let entries = (try? fileManager.contentsOfDirectory(atPath: candidate.path)) ?? []
            if entries.contains("Package.swift") || entries.contains(where: { $0.hasSuffix(".xcodeproj") }) {
                return candidate
            }
            candidate.deleteLastPathComponent()
        }
        return directory
    }

    static func swiftFiles(in root: URL) throws -> [URL] {
        let skipped = Set([".build", ".git", "BackendAPIReference", "Tests", "DerivedData"])
        let keys: Set<URLResourceKey> = [.isRegularFileKey, .isDirectoryKey]
        let enumerator = FileManager.default.enumerator(at: root, includingPropertiesForKeys: Array(keys), options: [.skipsHiddenFiles])
        var files: [URL] = []
        while let url = enumerator?.nextObject() as? URL {
            let values = try url.resourceValues(forKeys: keys)
            if values.isDirectory == true, skipped.contains(url.lastPathComponent) {
                enumerator?.skipDescendants()
            } else if values.isRegularFile == true, url.pathExtension == "swift" {
                files.append(url)
            }
        }
        return files
    }

    static func parseServers(_ documents: [(URL, String)]) -> [Server] {
        var servers: [Server] = []
        let referenceDocuments = documents + networkingKitDocuments()
        let defaults = defaultConfigurationItems(in: referenceDocuments)
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:final\s+)?(?:class|struct)\s+(\w+)\s*:\s*[^\{]*(?:NetworkClient|SharedNetworkClient)[^\{]*\{(.*?)\n\}"#)
        let baseURL = try! NSRegularExpression(pattern: #"baseURL\s*=\s*URL\s*\(\s*string:\s*\"([^\"]+)\"\s*\)\s*!"#)
        let configuration = try! NSRegularExpression(pattern: #"configuration\s*=\s*([^\n]+)"#)
        for (_, source) in documents {
            for match in declaration.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                let body = capture(2, from: source, match: match)
                guard let urlMatch = baseURL.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) else { continue }
                let name = capture(1, from: source, match: match)
                let config = configuration.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).trimmingCharacters(in: .whitespaces) } ?? "NetworkConfiguration.default"
                let resolvedConfiguration = resolveConfiguration(config, in: referenceDocuments)
                let overrides = configurationItems(from: resolveStaticReferences(in: resolvedConfiguration, documents: referenceDocuments))
                servers.append(Server(
                    name: name,
                    baseURL: capture(1, from: body, match: urlMatch),
                    configuration: mergedConfiguration(defaults: defaults, overrides: overrides)
                ))
            }
        }
        return servers
    }

    static func resolveConfiguration(_ reference: String, in documents: [(URL, String)]) -> String {
        if reference == "NetworkConfiguration.default" { return "NetworkConfiguration()" }
        guard let typeName = reference.split(separator: ".").first, reference.hasSuffix(".default") else { return reference }
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:enum|struct|class)\s+\#(typeName)\s*\{(.*?)\n\}"#)
        let defaultValue = try! NSRegularExpression(pattern: #"(?s)static\s+let\s+`?default`?\s*=\s*(NetworkConfiguration\(.*?\n\s*\))"#)
        for (_, source) in documents {
            guard let declarationMatch = declaration.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else { continue }
            let body = capture(1, from: source, match: declarationMatch)
            if let valueMatch = defaultValue.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) {
                return capture(1, from: body, match: valueMatch).replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
            }
        }
        return reference
    }

    static func networkingKitDocuments() -> [(URL, String)] {
        let sourceURL = URL(fileURLWithPath: #filePath)
        let packageRoot = sourceURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        return (try? swiftFiles(in: packageRoot).compactMap { url in
            guard url.path.contains("/Sources/NetworkingKit/") else { return nil }
            return try? (url, String(contentsOf: url, encoding: .utf8))
        }) ?? []
    }

    static func parseProtocolClients(_ documents: [(URL, String)]) -> [String: String] {
        let expression = try! NSRegularExpression(pattern: #"(?:protocol|extension)\s+(\w+)\s*:\s*NetworkRequest\s+where\s+Client\s*==\s*(\w+)"#)
        var clients: [String: String] = [:]
        for (_, source) in documents {
            for match in expression.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                clients[capture(1, from: source, match: match)] = capture(2, from: source, match: match)
            }
        }
        return clients
    }

    static func parseEndpoints(_ documents: [(URL, String)], protocolClients: [String: String], root: URL) -> [Endpoint] {
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:public|private|internal)?\s*(?:final\s+)?(?:struct|class)\s+(\w+)\s*:\s*([^\{]+)\{(.*?)\n\}"#)
        // A stored property ends at `=` or a newline. This intentionally excludes
        // computed request members such as `var path: String { ... }`.
        let property = try! NSRegularExpression(pattern: #"(?:private\s+|public\s+|internal\s+)?(?:let|var)\s+(\w+)\s*:\s*([^=\n\{]+)(?=\s*(?:=|\n))"#)
        let path = try! NSRegularExpression(pattern: #"var\s+path\s*:\s*String\s*\{\s*([^\}]+)\}"#)
        let method = try! NSRegularExpression(pattern: #"var\s+method\s*:\s*HTTPMethod\s*\{\s*\.([a-zA-Z]+)\s*\}"#)
        var endpoints: [Endpoint] = []

        for (url, source) in documents {
            for match in declaration.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                let inherited = capture(2, from: source, match: match)
                let kind: String
                if inherited.contains("RestfulRequest") { kind = "REST" }
                else if inherited.contains("GraphQLRequest") { kind = "GraphQL" }
                else { continue }
                guard let protocolName = protocolClients.keys.first(where: { inherited.contains($0) }), let server = protocolClients[protocolName] else { continue }
                let body = capture(3, from: source, match: match)
                let name = capture(1, from: source, match: match)
                var params = property.matches(in: body, range: NSRange(body.startIndex..., in: body)).map { "\(capture(1, from: body, match: $0)): \(capture(2, from: body, match: $0).trimmingCharacters(in: .whitespaces))" }
                let feature = feature(before: match.range.location, in: source)
                let relativePath: String
                let httpMethod: String
                if kind == "GraphQL" {
                    relativePath = "/graphql"
                    httpMethod = "POST"
                    params.append(contentsOf: graphQLParameters(in: body, excluding: params))
                } else {
                    relativePath = path.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).trimmingCharacters(in: .whitespaces) } ?? "<dynamic>"
                    httpMethod = method.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).uppercased() } ?? "<dynamic>"
                }
                let location = url.path.replacingOccurrences(of: root.path + "/", with: "")
                endpoints.append(Endpoint(name: name, server: server, feature: feature, method: httpMethod, path: relativePath, parameters: params, requestKind: kind, source: location))
            }
        }
        return endpoints
    }

    static func graphQLParameters(in body: String, excluding existing: [String]) -> [String] {
        // GraphQLRequest serializes query, variables, and operationName into its JSON body.
        // Capture both stored and single-line computed declarations; multi-line expressions
        // remain explicitly dynamic rather than pretending to know their runtime value.
        let member = try! NSRegularExpression(pattern: #"(?m)^\s*(?:private\s+|public\s+|internal\s+)?(?:let|var)\s+(query|variables|operationName)\b(?:\s*:\s*[^=\{\n]+)?\s*(?:=\s*([^\n]+)|\{\s*(.*)\}\s*$)"#)
        var names = Set(existing.compactMap { $0.split(separator: ":", maxSplits: 1).first.map(String.init) })
        var parameters: [String] = []
        for match in member.matches(in: body, range: NSRange(body.startIndex..., in: body)) {
            let name = capture(1, from: body, match: match)
            guard names.insert(name).inserted else { continue }
            let expression = captureOptional(2, from: body, match: match)
                ?? captureOptional(3, from: body, match: match)
                ?? "<dynamic>"
            parameters.append("\(name): \(expression.trimmingCharacters(in: .whitespaces))")
        }
        if !names.contains("query"), body.range(of: #"\b(?:let|var)\s+query\b"#, options: .regularExpression) != nil {
            parameters.append("query: <dynamic>")
        }
        return parameters
    }

    static func parameterHTML(_ parameter: String) -> String {
        if parameter.hasPrefix("query: ") {
            let source = String(parameter.dropFirst("query: ".count))
            return graphQLCodeBlock(name: "query", source: formatGraphQLQuery(source))
        }
        if parameter.hasPrefix("variables: ") {
            let source = String(parameter.dropFirst("variables: ".count))
            return graphQLCodeBlock(name: "variables", source: formatGraphQLVariables(source))
        }
        return escape(parameter)
    }

    static func graphQLCodeBlock(name: String, source: String) -> String {
        "<div class=\"graphql-input\"><span>\(escape(name))</span><pre><code>\(escape(source))</code></pre></div>"
    }

    static func formatGraphQLQuery(_ source: String) -> String {
        var query = source.trimmingCharacters(in: .whitespacesAndNewlines)
        if query.hasPrefix("\"") && query.hasSuffix("\"") && query.count >= 2 {
            query.removeFirst()
            query.removeLast()
        }
        query = query.replacingOccurrences(of: #"\n"#, with: "\n").replacingOccurrences(of: #"\""#, with: "\"")

        var lines: [String] = []
        var current = ""
        var indentation = 0
        var parenthesisDepth = 0
        func appendCurrent() {
            let trimmed = current.trimmingCharacters(in: .whitespaces)
            guard !trimmed.isEmpty else { return }
            lines.append(String(repeating: "  ", count: indentation) + trimmed)
            current = ""
        }

        for character in query {
            switch character {
            case "(":
                parenthesisDepth += 1
                current.append(character)
            case ")":
                parenthesisDepth = max(0, parenthesisDepth - 1)
                current.append(character)
            case "{":
                let trimmed = current.trimmingCharacters(in: .whitespaces)
                lines.append(String(repeating: "  ", count: indentation) + (trimmed.isEmpty ? "{" : trimmed + " {"))
                current = ""
                indentation += 1
            case "}":
                appendCurrent()
                indentation = max(0, indentation - 1)
                lines.append(String(repeating: "  ", count: indentation) + "}")
            case " ", "\t", "\n":
                if indentation > 0 && parenthesisDepth == 0 {
                    appendCurrent()
                } else if !current.hasSuffix(" ") {
                    current.append(" ")
                }
            default:
                current.append(character)
            }
        }
        appendCurrent()
        var normalized: [String] = []
        for line in lines {
            if line.trimmingCharacters(in: .whitespaces) == "{", !normalized.isEmpty {
                normalized[normalized.count - 1] += " {"
            } else {
                normalized.append(line)
            }
        }
        return normalized.joined(separator: "\n")
    }

    static func formatGraphQLVariables(_ source: String) -> String {
        var lines: [String] = []
        var current = ""
        var indentation = 0
        var parenthesisDepth = 0
        func appendCurrent() {
            let trimmed = current.trimmingCharacters(in: .whitespaces)
            guard !trimmed.isEmpty else { return }
            lines.append(String(repeating: "  ", count: indentation) + trimmed)
            current = ""
        }

        for character in source.trimmingCharacters(in: .whitespacesAndNewlines) {
            switch character {
            case "(":
                parenthesisDepth += 1
                current.append(character)
            case ")":
                parenthesisDepth = max(0, parenthesisDepth - 1)
                current.append(character)
            case "[", "{":
                let trimmed = current.trimmingCharacters(in: .whitespaces)
                lines.append(String(repeating: "  ", count: indentation) + trimmed + String(character))
                current = ""
                indentation += 1
            case "]", "}":
                appendCurrent()
                indentation = max(0, indentation - 1)
                lines.append(String(repeating: "  ", count: indentation) + String(character))
            case "," where parenthesisDepth == 0:
                current.append(character)
                appendCurrent()
            case " ", "\t", "\n":
                if !current.hasSuffix(" ") { current.append(" ") }
            default:
                current.append(character)
            }
        }
        appendCurrent()
        return lines.joined(separator: "\n")
    }

    static func feature(before offset: Int, in source: String) -> String {
        let prefix = String(source.prefix(offset))
        let marks = prefix.components(separatedBy: .newlines).filter { $0.range(of: #"^\s*//\s*MARK:\s*-\s*"#, options: .regularExpression) != nil }
        guard let mark = marks.last else { return "Other" }
        return mark.replacingOccurrences(of: #"^\s*//\s*MARK:\s*-\s*"#, with: "", options: .regularExpression).trimmingCharacters(in: .whitespaces)
    }

    static func writeIndex(servers: [Server], endpoints: [Endpoint], to directory: URL) throws {
        let cards = servers.map { server in
            let filename = pageName(for: server)
            let count = endpoints.filter { $0.server == server.name }.count
            return "<a class=\"server-card\" data-search=\"\(escape(server.name + " " + server.baseURL))\" href=\"\(escape(filename))\"><span class=\"card-kicker\">BACKEND SERVER</span><h2>\(escape(server.name))</h2><code>\(escape(server.baseURL))</code><span class=\"count-badge\">\(count) 个端点</span></a>"
        }.joined(separator: "\n")
        let body = "<header class=\"hero\"><div class=\"page-width\"><p class=\"eyebrow\">NETWORKINGKIT</p><h1>后端 API 文档</h1><p class=\"lede\">由 App 源码自动生成 · 共 \(servers.count) 个后端服务器，\(endpoints.count) 个端点</p></div></header><main class=\"page-width\"><input class=\"search\" type=\"search\" placeholder=\"筛选服务器、URL 或端点…\" aria-label=\"筛选服务器\" data-filter><div class=\"chip-row\"><span class=\"chip\">\(servers.count) 个服务器</span><span class=\"chip\">\(endpoints.count) 个端点</span></div><section class=\"card-grid\" data-filter-container>\(cards)</section><p class=\"empty\" hidden>没有匹配的服务器。</p></main>"
        try html(title: "Backend API Reference", body: body).write(to: directory.appendingPathComponent("index.html"), atomically: true, encoding: .utf8)
    }

    static func writeServerPage(_ server: Server, endpoints: [Endpoint], to directory: URL) throws {
        let groups = Dictionary(grouping: endpoints, by: \.feature).sorted { $0.key < $1.key }.map { feature, endpoints in
            let rows = endpoints.sorted { $0.name < $1.name }.map { endpoint in
                let parameters = endpoint.parameters.isEmpty ? "—" : endpoint.parameters.map(parameterHTML).joined(separator: "<br>")
                return "<tr data-search=\"\(escape(endpoint.name + " " + endpoint.path + " " + endpoint.parameters.joined(separator: " ") + " " + endpoint.source))\"><td><span class=\"method method-\(escape(endpoint.method.lowercased()))\">\(escape(endpoint.method))</span></td><td><code>\(escape(endpoint.path))</code></td><td>\(escape(endpoint.requestKind))</td><td>\(parameters)</td><td><code>\(escape(endpoint.name))</code></td><td><code>\(escape(endpoint.source))</code></td></tr>"
            }.joined()
            let search = endpoints.map { $0.feature + " " + $0.name + " " + $0.path + " " + $0.parameters.joined(separator: " ") }.joined(separator: " ")
            return "<section class=\"feature-card\" data-search=\"\(escape(search))\"><div class=\"feature-heading\"><div><p class=\"card-kicker\">FEATURE</p><h2>\(escape(feature))</h2></div><span class=\"count-badge\">\(endpoints.count) 个端点</span></div><div class=\"table-wrap\"><table><thead><tr><th>Method</th><th>Endpoint</th><th>Kind</th><th>Parameters</th><th>Request</th><th>Source</th></tr></thead><tbody>\(rows)</tbody></table></div></section>"
        }.joined(separator: "\n")
        let configurationRows = server.configuration.map { key, value in
            "<tr><td>\(escape(key))</td><td><code>\(escape(value))</code></td></tr>"
        }.joined()
        let configurationTable = "<section class=\"feature-card configuration\"><div class=\"feature-heading\"><div><p class=\"card-kicker\">CLIENT CONFIGURATION</p><h2>配置</h2></div></div><div class=\"table-wrap\"><table><thead><tr><th>配置项</th><th>值</th></tr></thead><tbody>\(configurationRows)</tbody></table></div></section>"
        let body = "<header class=\"hero compact\"><div class=\"page-width\"><a class=\"back\" href=\"index.html\">← 所有服务器</a><p class=\"eyebrow\">BACKEND SERVER</p><h1>\(escape(server.name))</h1><p class=\"lede\"><code>\(escape(server.baseURL))</code> · \(endpoints.count) 个端点</p></div></header><main class=\"page-width\"><input class=\"search\" type=\"search\" placeholder=\"筛选 Feature、端点、参数、Request 或 Source…\" aria-label=\"筛选端点\" data-filter>\(configurationTable)<section class=\"feature-list\" data-filter-container>\(groups.isEmpty ? "<p class=\"empty\">没有可静态识别的端点。</p>" : groups)</section><p class=\"empty\" hidden>没有匹配的端点。</p></main>"
        try html(title: server.name, body: body).write(to: directory.appendingPathComponent(pageName(for: server)), atomically: true, encoding: .utf8)
    }

    static func configurationItems(from configuration: String) -> [(String, String)] {
        guard configuration.hasPrefix("NetworkConfiguration("), configuration.hasSuffix(")") else {
            return configuration == "NetworkConfiguration.default" ? [] : [("Configuration", configuration)]
        }
        let inner = String(configuration.dropFirst("NetworkConfiguration(".count).dropLast())
        return topLevelItems(in: inner).map { item in
            let pair = item.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
            guard pair.count == 2 else { return (item.trimmingCharacters(in: .whitespaces), "") }
            return (pair[0].trimmingCharacters(in: .whitespaces), pair[1].trimmingCharacters(in: .whitespaces))
        }
    }

    static func topLevelItems(in value: String) -> [String] {
        var items: [String] = []
        var current = ""
        var depth = 0
        for character in value {
            switch character {
            case "(", "[", "{": depth += 1
            case ")", "]", "}": depth -= 1
            case "," where depth == 0:
                items.append(current)
                current = ""
                continue
            default: break
            }
            current.append(character)
        }
        if !current.isEmpty { items.append(current) }
        return items
    }

    static func defaultConfigurationItems(in documents: [(URL, String)]) -> [(String, String)] {
        let initializer = try! NSRegularExpression(pattern: #"(?s)public\s+init\s*\((.*?)\)\s*\{"#)
        for (_, source) in documents where source.contains("struct NetworkConfiguration") {
            guard let match = initializer.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else { continue }
            let parameters = capture(1, from: source, match: match)
            let defaults = topLevelItems(in: parameters).compactMap { parameter -> (String, String)? in
                let parts = parameter.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
                guard parts.count == 2 else { return nil }
                let name = parts[0].split(separator: ":", maxSplits: 1).first?.trimmingCharacters(in: .whitespacesAndNewlines)
                guard let name, !name.isEmpty else { return nil }
                return (name, parts[1].trimmingCharacters(in: .whitespacesAndNewlines))
            }
            return defaults.map { ($0.0, resolveStaticReferences(in: $0.1, documents: documents)) }
        }
        return []
    }

    static func mergedConfiguration(defaults: [(String, String)], overrides: [(String, String)]) -> [(String, String)] {
        var effective = defaults
        for (key, value) in overrides {
            if let index = effective.firstIndex(where: { $0.0 == key }) {
                effective[index] = (key, value)
            } else {
                effective.append((key, value))
            }
        }
        return effective
    }

    static func resolveStaticReferences(in value: String, documents: [(URL, String)]) -> String {
        // Values in NetworkConfiguration often use app constants, for example
        // `DemoConstants.requestTimeout`. Resolve those references without
        // evaluating arbitrary Swift code.
        let qualifiedReference = try! NSRegularExpression(pattern: #"\b(\w+)\.(\w+)\.(\w+)\b"#)
        let reference = try! NSRegularExpression(pattern: #"\b(\w+)\.(\w+)\b"#)
        var resolved = value
        for _ in 0..<4 {
            var replacements: [(NSRange, String)] = []
            for match in qualifiedReference.matches(in: resolved, range: NSRange(resolved.startIndex..., in: resolved)) {
                let type = capture(1, from: resolved, match: match)
                let member = capture(3, from: resolved, match: match)
                if let constant = staticConstant(named: member, in: type, documents: documents) {
                    replacements.append((match.range, constant))
                }
            }
            for match in reference.matches(in: resolved, range: NSRange(resolved.startIndex..., in: resolved)) where !replacements.contains(where: { NSIntersectionRange($0.0, match.range).length > 0 }) {
                let type = capture(1, from: resolved, match: match)
                let member = capture(2, from: resolved, match: match)
                if let constant = staticConstant(named: member, in: type, documents: documents) {
                    replacements.append((match.range, constant))
                }
            }
            guard !replacements.isEmpty else { break }
            for (range, replacement) in replacements.reversed() {
                guard let swiftRange = Range(range, in: resolved) else { continue }
                resolved.replaceSubrange(swiftRange, with: replacement)
            }
        }
        return resolved
    }

    static func staticConstant(named member: String, in type: String, documents: [(URL, String)]) -> String? {
        let declaration = try! NSRegularExpression(
            pattern: #"(?s)(?:enum|struct|class)\s+\#(type)\s*\{(.*?)^\}"#,
            options: [.anchorsMatchLines]
        )
        let constant = try! NSRegularExpression(
            pattern: #"(?m)^\s*(?:public\s+)?static\s+let\s+\#(member)(?:\s*:\s*[^=\n]+)?\s*=\s*([^\n]+)"#
        )
        for (_, source) in documents {
            guard let typeMatch = declaration.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else { continue }
            let body = capture(1, from: source, match: typeMatch)
            if let valueMatch = constant.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) {
                return capture(1, from: body, match: valueMatch).trimmingCharacters(in: .whitespaces)
            }
        }
        return nil
    }

    static func pageName(for server: Server) -> String { server.name + ".html" }
    static func capture(_ index: Int, from string: String, match: NSTextCheckingResult) -> String { String(string[Range(match.range(at: index), in: string)!]) }
    static func captureOptional(_ index: Int, from string: String, match: NSTextCheckingResult) -> String? {
        let range = match.range(at: index)
        guard range.location != NSNotFound, let swiftRange = Range(range, in: string) else { return nil }
        return String(string[swiftRange])
    }
    static func escape(_ value: String) -> String { value.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "<", with: "&lt;").replacingOccurrences(of: ">", with: "&gt;").replacingOccurrences(of: "\"", with: "&quot;") }
    static func html(title: String, body: String) -> String { """
    <!doctype html><html lang="zh-Hans"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>\(escape(title))</title><style>
    :root{color-scheme:dark;--bg:#101112;--surface:#171819;--line:#343638;--text:#f7f7f5;--muted:#96999d;--blue:#8cbfff;--blue-bg:#172944}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px -apple-system,BlinkMacSystemFont,"SF Pro Display","PingFang SC",sans-serif}.page-width{max-width:1788px;margin:auto;padding-left:clamp(24px,5.4vw,104px);padding-right:clamp(24px,5.4vw,104px)}.hero{background:#0e1822;border-bottom:1px solid var(--line);padding:88px 0 68px}.hero.compact{padding:46px 0}.eyebrow,.card-kicker{margin:0 0 12px;color:var(--muted);font-size:13px;font-weight:750;letter-spacing:.12em}.hero h1{margin:0;font-size:clamp(44px,5vw,78px);line-height:1.05;letter-spacing:-.055em}.lede{margin:24px 0 0;color:var(--muted);font-size:21px;font-weight:600}.back{display:inline-block;margin-bottom:26px;color:var(--blue);font-weight:700;text-decoration:none}main{padding-top:62px;padding-bottom:100px}.search{width:100%;border:3px solid var(--blue);outline:0;border-radius:17px;background:#141516;color:var(--text);padding:20px 22px;font:600 21px inherit;box-shadow:0 0 0 1px #29486f}.search::placeholder{color:#6f7378}.chip-row{display:flex;gap:12px;margin:34px 0 42px}.chip,.count-badge{display:inline-flex;align-items:center;border-radius:999px;background:var(--blue-bg);color:#dceaff;font-weight:750}.chip{padding:10px 15px;border:1px solid #29486f}.count-badge{padding:9px 13px;font-size:14px;white-space:nowrap}.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:22px}.server-card,.feature-card{border:1px solid var(--line);border-radius:22px;background:var(--surface);box-shadow:0 15px 42px #0000002b}.server-card{display:block;min-height:220px;padding:31px;color:var(--text);text-decoration:none;transition:transform .15s,border-color .15s}.server-card:hover{transform:translateY(-3px);border-color:var(--blue)}.server-card h2,.feature-heading h2{margin:0;font-size:30px;letter-spacing:-.035em}.server-card code{display:block;margin-top:18px;color:#c8d6e9;overflow-wrap:anywhere}.server-card .count-badge{margin-top:26px}.feature-list{display:grid;gap:28px;margin-top:34px}.feature-card{margin-top:34px;padding:30px}.feature-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:30px}.table-wrap{overflow:auto}table{width:100%;min-width:820px;border-collapse:collapse;text-align:left}th{color:var(--muted);font-size:14px;letter-spacing:.07em;text-transform:uppercase}th,td{padding:17px;border-bottom:1px solid var(--line);vertical-align:top}tbody tr:last-child td{border-bottom:0}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.92em;overflow-wrap:anywhere}.method{display:inline-block;border-radius:7px;padding:6px 8px;background:#24364f;color:#cfe4ff;font:750 12px ui-monospace,SFMono-Regular,Menlo}.method-post{background:#263f32;color:#b6e5c6}.method-delete{background:#482c31;color:#ffc5cb}.empty{margin:40px 0;color:var(--muted);text-align:center}@media(max-width:700px){.hero{padding:58px 0 48px}.lede{font-size:17px}.feature-card{padding:21px}.feature-heading{display:block}.feature-heading .count-badge{margin-top:16px}.search{font-size:17px;padding:17px}}
    </style><style>.graphql-input{display:grid;gap:7px}.graphql-input>span{color:var(--muted);font:750 12px ui-monospace,SFMono-Regular,Menlo}.graphql-input pre{max-width:560px;margin:0;padding:13px 15px;overflow:auto;border:1px solid #29486f;border-radius:10px;background:#101924;white-space:pre}.graphql-input pre code{color:#dceaff;font-size:13px;line-height:1.55}</style></head><body>\(body)<script>const input=document.querySelector('[data-filter]');if(input){const items=[...document.querySelectorAll('[data-search]')],empty=document.querySelector('.empty[hidden]');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();let visible=0;items.forEach(item=>{const show=!q||item.dataset.search.toLowerCase().includes(q);item.hidden=!show;if(show)visible++});if(empty)empty.hidden=visible>0})}</script></body></html>
    """ }
}

enum GeneratorError: Error { case invalidArguments }

try BackendReferenceGenerator.run()
