import Foundation

struct Server {
    let name: String
    let baseURL: String
    let configuration: String
}

struct Endpoint {
    let name: String
    let server: String
    let feature: String
    let method: String
    let path: String
    let parameters: [String]
    let requestKind: String
    let source: String
}

enum BackendReferenceGenerator {
    static func run() throws {
        let arguments = Array(CommandLine.arguments.dropFirst())
        guard let sourceDirectory = value(after: "--source-directory", in: arguments),
              let stamp = value(after: "--stamp", in: arguments) else {
            throw GeneratorError.invalidArguments
        }

        let sourceURL = URL(fileURLWithPath: sourceDirectory)
        let projectRoot = findProjectRoot(startingAt: sourceURL)
        let outputDirectory = value(after: "--output-directory", in: arguments)
            .map(URL.init(fileURLWithPath:))
            ?? projectRoot.appendingPathComponent("BackendAPIReference", isDirectory: true)
        let files = try swiftFiles(in: projectRoot)
        let documents = try files.map { url in (url, try String(contentsOf: url, encoding: .utf8)) }
        let servers = parseServers(documents)
        let protocolClients = parseProtocolClients(documents)
        let endpoints = parseEndpoints(documents, protocolClients: protocolClients, root: projectRoot)

        try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        try writeIndex(servers: servers, endpoints: endpoints, to: outputDirectory)
        for server in servers {
            try writeServerPage(server, endpoints: endpoints.filter { $0.server == server.name }, to: outputDirectory)
        }
        try "Generated by BackendReferencePlugin\n".write(to: URL(fileURLWithPath: stamp), atomically: true, encoding: .utf8)
    }

    static func value(after option: String, in arguments: [String]) -> String? {
        guard let index = arguments.firstIndex(of: option), arguments.indices.contains(index + 1) else { return nil }
        return arguments[index + 1]
    }

    static func findProjectRoot(startingAt directory: URL) -> URL {
        let fileManager = FileManager.default
        var candidate = directory
        while candidate.path != "/" {
            let entries = (try? fileManager.contentsOfDirectory(atPath: candidate.path)) ?? []
            if entries.contains("Package.swift") || entries.contains(where: { $0.hasSuffix(".xcodeproj") }) {
                return candidate
            }
            candidate.deleteLastPathComponent()
        }
        return directory
    }

    static func swiftFiles(in root: URL) throws -> [URL] {
        let skipped = Set([".build", ".git", "BackendAPIReference", "Tests", "DerivedData"])
        let keys: Set<URLResourceKey> = [.isRegularFileKey, .isDirectoryKey]
        let enumerator = FileManager.default.enumerator(at: root, includingPropertiesForKeys: Array(keys), options: [.skipsHiddenFiles])
        var files: [URL] = []
        while let url = enumerator?.nextObject() as? URL {
            let values = try url.resourceValues(forKeys: keys)
            if values.isDirectory == true, skipped.contains(url.lastPathComponent) {
                enumerator?.skipDescendants()
            } else if values.isRegularFile == true, url.pathExtension == "swift" {
                files.append(url)
            }
        }
        return files
    }

    static func parseServers(_ documents: [(URL, String)]) -> [Server] {
        var servers: [Server] = []
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:final\s+)?(?:class|struct)\s+(\w+)\s*:\s*[^\{]*(?:NetworkClient|SharedNetworkClient)[^\{]*\{(.*?)\n\}"#)
        let baseURL = try! NSRegularExpression(pattern: #"baseURL\s*=\s*URL\s*\(\s*string:\s*\"([^\"]+)\"\s*\)\s*!"#)
        let configuration = try! NSRegularExpression(pattern: #"configuration\s*=\s*([^\n]+)"#)
        for (_, source) in documents {
            for match in declaration.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                let body = capture(2, from: source, match: match)
                guard let urlMatch = baseURL.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) else { continue }
                let name = capture(1, from: source, match: match)
                let config = configuration.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).trimmingCharacters(in: .whitespaces) } ?? "NetworkConfiguration.default"
                let resolvedConfiguration = resolveConfiguration(config, in: documents)
                servers.append(Server(name: name, baseURL: capture(1, from: body, match: urlMatch), configuration: resolveStaticReferences(in: resolvedConfiguration, documents: documents)))
            }
        }
        return servers
    }

    static func resolveConfiguration(_ reference: String, in documents: [(URL, String)]) -> String {
        guard let typeName = reference.split(separator: ".").first, reference.hasSuffix(".default") else { return reference }
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:enum|struct|class)\s+\#(typeName)\s*\{(.*?)\n\}"#)
        let defaultValue = try! NSRegularExpression(pattern: #"(?s)static\s+let\s+`?default`?\s*=\s*(NetworkConfiguration\(.*?\n\s*\))"#)
        for (_, source) in documents {
            guard let declarationMatch = declaration.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else { continue }
            let body = capture(1, from: source, match: declarationMatch)
            if let valueMatch = defaultValue.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) {
                return capture(1, from: body, match: valueMatch).replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
            }
        }
        return reference
    }

    static func parseProtocolClients(_ documents: [(URL, String)]) -> [String: String] {
        let expression = try! NSRegularExpression(pattern: #"(?:protocol|extension)\s+(\w+)\s*:\s*NetworkRequest\s+where\s+Client\s*==\s*(\w+)"#)
        var clients: [String: String] = [:]
        for (_, source) in documents {
            for match in expression.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                clients[capture(1, from: source, match: match)] = capture(2, from: source, match: match)
            }
        }
        return clients
    }

    static func parseEndpoints(_ documents: [(URL, String)], protocolClients: [String: String], root: URL) -> [Endpoint] {
        let declaration = try! NSRegularExpression(pattern: #"(?s)(?:public|private|internal)?\s*(?:final\s+)?(?:struct|class)\s+(\w+)\s*:\s*([^\{]+)\{(.*?)\n\}"#)
        // A stored property ends at `=` or a newline. This intentionally excludes
        // computed request members such as `var path: String { ... }`.
        let property = try! NSRegularExpression(pattern: #"(?:private\s+|public\s+|internal\s+)?(?:let|var)\s+(\w+)\s*:\s*([^=\n\{]+)(?=\s*(?:=|\n))"#)
        let path = try! NSRegularExpression(pattern: #"var\s+path\s*:\s*String\s*\{\s*([^\}]+)\}"#)
        let method = try! NSRegularExpression(pattern: #"var\s+method\s*:\s*HTTPMethod\s*\{\s*\.([a-zA-Z]+)\s*\}"#)
        var endpoints: [Endpoint] = []

        for (url, source) in documents {
            for match in declaration.matches(in: source, range: NSRange(source.startIndex..., in: source)) {
                let inherited = capture(2, from: source, match: match)
                let kind: String
                if inherited.contains("RestfulRequest") { kind = "REST" }
                else if inherited.contains("GraphQLRequest") { kind = "GraphQL" }
                else { continue }
                guard let protocolName = protocolClients.keys.first(where: { inherited.contains($0) }), let server = protocolClients[protocolName] else { continue }
                let body = capture(3, from: source, match: match)
                let name = capture(1, from: source, match: match)
                let params = property.matches(in: body, range: NSRange(body.startIndex..., in: body)).map { "\(capture(1, from: body, match: $0)): \(capture(2, from: body, match: $0).trimmingCharacters(in: .whitespaces))" }
                let feature = feature(before: match.range.location, in: source)
                let relativePath: String
                let httpMethod: String
                if kind == "GraphQL" {
                    relativePath = "/graphql"
                    httpMethod = "POST"
                } else {
                    relativePath = path.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).trimmingCharacters(in: .whitespaces) } ?? "<dynamic>"
                    httpMethod = method.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)).map { capture(1, from: body, match: $0).uppercased() } ?? "<dynamic>"
                }
                let location = url.path.replacingOccurrences(of: root.path + "/", with: "")
                endpoints.append(Endpoint(name: name, server: server, feature: feature, method: httpMethod, path: relativePath, parameters: params, requestKind: kind, source: location))
            }
        }
        return endpoints
    }

    static func feature(before offset: Int, in source: String) -> String {
        let prefix = String(source.prefix(offset))
        let marks = prefix.components(separatedBy: .newlines).filter { $0.range(of: #"^\s*//\s*MARK:\s*-\s*"#, options: .regularExpression) != nil }
        guard let mark = marks.last else { return "Other" }
        return mark.replacingOccurrences(of: #"^\s*//\s*MARK:\s*-\s*"#, with: "", options: .regularExpression).trimmingCharacters(in: .whitespaces)
    }

    static func writeIndex(servers: [Server], endpoints: [Endpoint], to directory: URL) throws {
        let cards = servers.map { server in
            let filename = pageName(for: server)
            return "<li><a href=\"\(escape(filename))\"><strong>\(escape(server.name))</strong><span>\(escape(server.baseURL))</span><small>\(endpoints.filter { $0.server == server.name }.count) endpoints</small></a></li>"
        }.joined(separator: "\n")
        try html(title: "Backend API Reference", body: "<h1>Backend API Reference</h1><p>Generated from the app source during build.</p><ul class=\"servers\">\(cards)</ul>").write(to: directory.appendingPathComponent("index.html"), atomically: true, encoding: .utf8)
    }

    static func writeServerPage(_ server: Server, endpoints: [Endpoint], to directory: URL) throws {
        let groups = Dictionary(grouping: endpoints, by: \.feature).sorted { $0.key < $1.key }.map { feature, endpoints in
            let rows = endpoints.sorted { $0.name < $1.name }.map { endpoint in
                let parameters = endpoint.parameters.isEmpty ? "—" : endpoint.parameters.map(escape).joined(separator: "<br>")
                return "<tr><td><code>\(escape(endpoint.method))</code></td><td><code>\(escape(endpoint.path))</code></td><td>\(escape(endpoint.requestKind))</td><td>\(parameters)</td><td><code>\(escape(endpoint.name))</code></td><td><code>\(escape(endpoint.source))</code></td></tr>"
            }.joined()
            return "<section><h2>\(escape(feature))</h2><table><thead><tr><th>Method</th><th>Endpoint</th><th>Kind</th><th>Parameters</th><th>Request</th><th>Source</th></tr></thead><tbody>\(rows)</tbody></table></section>"
        }.joined(separator: "\n")
        let configurationRows = configurationItems(from: server.configuration).map { key, value in
            "<tr><td>\(escape(key))</td><td><code>\(escape(value))</code></td></tr>"
        }.joined()
        let configurationTable = "<section><h2>Configuration</h2><table><thead><tr><th>Configuration</th><th>Value</th></tr></thead><tbody>\(configurationRows)</tbody></table></section>"
        let body = "<p><a href=\"index.html\">← All servers</a></p><h1>\(escape(server.name))</h1><p><strong>Base URL:</strong> <code>\(escape(server.baseURL))</code></p>\(configurationTable)\(groups.isEmpty ? "<p>No statically discoverable endpoints.</p>" : groups)"
        try html(title: server.name, body: body).write(to: directory.appendingPathComponent(pageName(for: server)), atomically: true, encoding: .utf8)
    }

    static func configurationItems(from configuration: String) -> [(String, String)] {
        guard configuration.hasPrefix("NetworkConfiguration("), configuration.hasSuffix(")") else {
            return [("Configuration", configuration)]
        }
        let inner = String(configuration.dropFirst("NetworkConfiguration(".count).dropLast())
        var items: [String] = []
        var current = ""
        var depth = 0
        for character in inner {
            switch character {
            case "(", "[", "{": depth += 1
            case ")", "]", "}": depth -= 1
            case "," where depth == 0:
                items.append(current)
                current = ""
                continue
            default: break
            }
            current.append(character)
        }
        if !current.isEmpty { items.append(current) }
        return items.map { item in
            let pair = item.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
            guard pair.count == 2 else { return (item.trimmingCharacters(in: .whitespaces), "") }
            return (pair[0].trimmingCharacters(in: .whitespaces), pair[1].trimmingCharacters(in: .whitespaces))
        }
    }

    static func resolveStaticReferences(in value: String, documents: [(URL, String)]) -> String {
        // Values in NetworkConfiguration often use app constants, for example
        // `DemoConstants.requestTimeout`. Resolve those references without
        // evaluating arbitrary Swift code.
        let reference = try! NSRegularExpression(pattern: #"\b(\w+)\.(\w+)\b"#)
        var resolved = value
        for _ in 0..<4 {
            let matches = reference.matches(in: resolved, range: NSRange(resolved.startIndex..., in: resolved))
            var replacements: [(NSRange, String)] = []
            for match in matches {
                let type = capture(1, from: resolved, match: match)
                let member = capture(2, from: resolved, match: match)
                if let constant = staticConstant(named: member, in: type, documents: documents) {
                    replacements.append((match.range, constant))
                }
            }
            guard !replacements.isEmpty else { break }
            for (range, replacement) in replacements.reversed() {
                guard let swiftRange = Range(range, in: resolved) else { continue }
                resolved.replaceSubrange(swiftRange, with: replacement)
            }
        }
        return resolved
    }

    static func staticConstant(named member: String, in type: String, documents: [(URL, String)]) -> String? {
        let declaration = try! NSRegularExpression(
            pattern: #"(?s)(?:enum|struct|class)\s+\#(type)\s*\{(.*?)^\}"#,
            options: [.anchorsMatchLines]
        )
        let constant = try! NSRegularExpression(
            pattern: #"(?m)^\s*static\s+let\s+\#(member)(?:\s*:\s*[^=\n]+)?\s*=\s*([^\n]+)"#
        )
        for (_, source) in documents {
            guard let typeMatch = declaration.firstMatch(in: source, range: NSRange(source.startIndex..., in: source)) else { continue }
            let body = capture(1, from: source, match: typeMatch)
            if let valueMatch = constant.firstMatch(in: body, range: NSRange(body.startIndex..., in: body)) {
                return capture(1, from: body, match: valueMatch).trimmingCharacters(in: .whitespaces)
            }
        }
        return nil
    }

    static func pageName(for server: Server) -> String { server.name + ".html" }
    static func capture(_ index: Int, from string: String, match: NSTextCheckingResult) -> String { String(string[Range(match.range(at: index), in: string)!]) }
    static func escape(_ value: String) -> String { value.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "<", with: "&lt;").replacingOccurrences(of: ">", with: "&gt;").replacingOccurrences(of: "\"", with: "&quot;") }
    static func html(title: String, body: String) -> String { "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>\(escape(title))</title><style>body{font:16px -apple-system,BlinkMacSystemFont,sans-serif;max-width:1100px;margin:48px auto;padding:0 24px;color:#172033}a{color:#1264d6;text-decoration:none}h1{margin-bottom:8px}.servers{padding:0;display:grid;gap:12px}.servers li{list-style:none;border:1px solid #dce3ef;border-radius:10px}.servers a{display:grid;padding:18px;gap:6px}.servers span,small{color:#526078}dl{display:grid;grid-template-columns:140px 1fr;gap:10px}dt{font-weight:600}dd{margin:0}section{margin-top:38px}table{border-collapse:collapse;width:100%;text-align:left}th,td{padding:12px;border-bottom:1px solid #dce3ef;vertical-align:top}th{background:#f5f7fb}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9em}</style></head><body>\(body)</body></html>" }
}

enum GeneratorError: Error { case invalidArguments }

try BackendReferenceGenerator.run()
